name = "cf-worker-ws-dev" # todo
#name = "cf-worker-connect-test" # todo
#main = "test/worker/cf-cdn-cgi-trace2.js"
#main = "test/worker/worker-connect-test.js"
main = "_worker.js"
compatibility_date = "2023-05-26"
[[routes]]
pattern = "vidio.kensoko.my.id"
custom_domain = true
[[routes]]
pattern = "quiz.vidio.com.vidio.kensoko.my.id"
custom_domain = true

[vars]
# UUID = "6baea179-0f18-4c98-a4a1-44c740d30cff"
# PROXYIP = "172.232.238.169"
# DNS_RESOLVER_URL = "https://cloudflare-dns.com/dns-query"
# NODE_ID = "1"
# API_TOKEN = "example_dev_token"
# API_HOST = "api.v2board.com"
UUID = "6baea179-0f18-4c98-a4a1-44c740d30cff"
